apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mk-app.fullname" . }}-secret
type: Opaque
data:
  # b64enc автоматично кодує рядок з values.yaml
  tele-token: {{ .Values.secrets.teleToken | b64enc | quote }}